name: Deploy CDK

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose whether to deploy or destroy the stack"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip show aws-cdk-lib
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Bootstrap CDK
        run: |
          cdk bootstrap aws://$AWS_ACCOUNT_ID/us-east-1
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

      - name: Deploy or Destroy Stack
        run: |
          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            echo " Deploying stack..."
            cdk deploy KachiCdkDemoStackDev --require-approval never
          else
            echo " Destroying stack..."
            cdk destroy KachiCdkDemoStackDev --force
          fi  