name: Deploy CDK

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment to deploy (dev/qa/prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod
      action:
        description: "Choose whether to deploy or destroy"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_${{ github.event.inputs.environment | upper }}')] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_${{ github.event.inputs.environment | upper }}')] }}
          aws-region: us-east-1

      - name: Deploy or Destroy Stack
        run: |
          STACK_NAME=""
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            STACK_NAME="DevEksStack"
          elif [ "${{ github.event.inputs.environment }}" == "qa" ]; then
            STACK_NAME="QaEksStack"
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            STACK_NAME="ProdEksStack"
          fi

          if [ "${{ github.event.inputs.action }}" == "deploy" ]; then
            echo " Deploying $STACK_NAME..."
            cdk deploy $STACK_NAME --require-approval never
          else
            echo " Destroying $STACK_NAME..."
            cdk destroy $STACK_NAME --force
          fi
